import 'dotenv/config';
import { PrismaClient } from '../app/generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

// ─── EJERCICIOS (37 entries from Valkyria_Biblioteca_Ejercicios.html) ────────

const EJERCICIOS = [
  { externalId:'sq1',movimiento:'sq',tipo:'variante',bloquesIdeal:['H','F'],rank:'S',nombre:'Sentadilla con pausa en el hoyo',altNombre:'Pause squat 2-3ct',musculosObjetivo:['Cuadriceps','Gluteo','Core'],transferencia:96,tecnicaClave:'Descendes hasta profundidad completa. Pausas 2-3 segundos sin rebote completamente quieto. Subes explosivo. La espalda no puede moverse durante la pausa.',cuandoUsarlo:'Atleta que falla en la salida del hoyo o zona media de la subida. Elimina el reflejo de estiramiento y obliga a generar fuerza pura desde abajo.',erroresComunes:'Rebotar al final de la pausa. Perder la tension del core. Pausar antes de la profundidad completa.',cargaRecomendada:'80-90% del RM de SQ. Reduce 5-8% respecto al basico por el esfuerzo de la pausa.',seriesRecomendadas:'4x3 progresando a 3x3 a lo largo del bloque de fuerza base',referencia:'pause squat powerlifting tutorial Bryce Lewis Calgary Barbell Alan Thrall'},
  { externalId:'sq2',movimiento:'sq',tipo:'variante',bloquesIdeal:['H','F'],rank:'S',nombre:'Sentadilla barra alta',altNombre:'High bar back squat',musculosObjetivo:['Cuadriceps','Gluteo','Tobillo'],transferencia:92,tecnicaClave:'Barra sobre los trapecios. Postura mas vertical que la barra baja. Rodillas viajan mas hacia adelante. ROM generalmente mayor. Profundidad completa siempre.',cuandoUsarlo:'Atleta de barra baja que necesita volumen de cuadriceps. Ideal para principiantes antes de aprender barra baja.',erroresComunes:'Barra sobre el cuello. Torso que colapsa hacia adelante. Talones que se despegan.',cargaRecomendada:'70-80% del RM de barra baja. El ROM mayor hace que pese menos.',seriesRecomendadas:'3x6-8 en hipertrofia. 4x4-5 en fuerza base',referencia:'high bar squat vs low bar tutorial Omar Isuf Squat University'},
  { externalId:'sq3',movimiento:'sq',tipo:'variante',bloquesIdeal:['H','F'],rank:'A',nombre:'Box squat',altNombre:'Sentadilla a caja',musculosObjetivo:['Gluteo','Cadena posterior','Cadera'],transferencia:80,tecnicaClave:'Caja a la altura del paralelo o abajo. Sentas completamente relajando el hip flexor. Pausas 1-2 seg. Subes empujando el suelo. Caderas hacia atras en la bajada.',cuandoUsarlo:'Atleta con fallo en la apertura de caderas o tendencia a colapsar las rodillas. Sistema Westside.',erroresComunes:'Rebotar en la caja. Caja demasiado alta. No sentarse completamente antes de subir.',cargaRecomendada:'60-75% del RM. El box cambia el patron cinematico.',seriesRecomendadas:'4x3-5. Siempre tecnica antes que peso',referencia:'box squat tutorial powerlifting Juggernaut Training Westside Barbell'},
  { externalId:'sq4',movimiento:'sq',tipo:'variante',bloquesIdeal:['H','F'],rank:'A',nombre:'Safety Bar Squat SSB',altNombre:'Barra especial de seguridad',musculosObjetivo:['Cuadriceps','Erectores','Core'],transferencia:78,tecnicaClave:'La barra tiene almohadilla frontal y asas. Centro de gravedad adelante igual a mas demanda de erectores. Postura similar a barra alta pero mas intensa en espalda.',cuandoUsarlo:'Atleta con movilidad limitada de hombros o munecas. Lesion en el brazo. Fortalece erectores debiles.',erroresComunes:'Dejar que la barra tire el torso hacia adelante. No mantener el pecho arriba activamente.',cargaRecomendada:'Similar a barra alta. El peso pesa mas por el brazo de palanca diferente.',seriesRecomendadas:'4x4-6',referencia:'safety squat bar SSB tutorial Alan Thrall Renaissance Periodization'},
  { externalId:'sq5',movimiento:'sq',tipo:'auxiliar',bloquesIdeal:['H'],rank:'S',nombre:'Hack squat en maquina',altNombre:'Hack squat machine',musculosObjetivo:['Cuadriceps','VMO'],transferencia:90,tecnicaClave:'Pies al ancho de caderas mitad-bajo de la plataforma. Bajas hasta 90 grados o mas. Sin bloquear rodillas arriba. Bajada controlada 2-3 seg.',cuandoUsarlo:'Sesion posterior a la sentadilla para acumular trabajo de cuadriceps sin cargar la columna.',erroresComunes:'Rodillas que colapsan hacia adentro. No llegar a 90 grados. Bloquear completamente arriba.',cargaRecomendada:'Moderado. Si el peso impide buena tecnica bajas.',seriesRecomendadas:'3-4x10-12 RIR 2-3',referencia:'hack squat form quads powerlifting Jeff Nippard Renaissance Periodization'},
  { externalId:'sq6',movimiento:'sq',tipo:'auxiliar',bloquesIdeal:['H','V'],rank:'A',nombre:'Prensa 45 grados',altNombre:'Leg press machine',musculosObjetivo:['Cuadriceps','Gluteo'],transferencia:82,tecnicaClave:'Rango completo. Pie alto mas gluteo. Pie bajo y estrecho mas cuadriceps. Nunca bloquees completamente las rodillas.',cuandoUsarlo:'Acumular volumen de piernas sin fatiga de columna. Ideal despues de la sentadilla pesada.',erroresComunes:'Rango parcial. Rodillas que colapsan. Retener el respaldo con las manos.',cargaRecomendada:'Moderado-alto.',seriesRecomendadas:'3x10-15. Tambien funciona en piramide ascendente',referencia:'leg press powerlifting accessory Mike Israetel Dr Milo Wolf'},
  { externalId:'sq7',movimiento:'sq',tipo:'auxiliar',bloquesIdeal:['H'],rank:'A',nombre:'Sentadilla bulgara',altNombre:'Bulgarian split squat RFESS',musculosObjetivo:['Cuadriceps','Gluteo','Estabilidad'],transferencia:74,tecnicaClave:'Pie trasero sobre banco a altura de rodilla. Bajas verticalmente. El femur frontal queda vertical al suelo. Torso ligeramente inclinado.',cuandoUsarlo:'Atleta con diferencia entre piernas. Alta carga interna con poco peso.',erroresComunes:'Pie trasero demasiado alto. Torso que colapsa. Rodilla frontal que colapsa hacia adentro.',cargaRecomendada:'Mancuernas livianas.',seriesRecomendadas:'3x8-10 por pierna RIR 2-3',referencia:'Bulgarian split squat tutorial Jeff Nippard ATG Knees Over Toes'},
  { externalId:'sq8',movimiento:'sq',tipo:'auxiliar',bloquesIdeal:['H','F'],rank:'A',nombre:'Good morning SQ',altNombre:'Buenos dias con barra',musculosObjetivo:['Erectores','Isquiotibiales','Gluteo'],transferencia:76,tecnicaClave:'Barra baja o alta. Rodillas ligeramente flexionadas. Bisagra de cadera llevando el torso hasta casi paralelo al suelo. Espalda NEUTRAL siempre.',cuandoUsarlo:'Atleta que hace buenos dias en la sentadilla: la cadera sube mas rapido que los hombros.',erroresComunes:'Espalda redondeada es peligroso. Doblar demasiado las rodillas. Peso excesivo.',cargaRecomendada:'Muy ligero al principio. El rango y el control importan mas que el peso.',seriesRecomendadas:'3x8-12. Velocidad controlada',referencia:'good morning exercise form powerlifting Alan Thrall Calgary Barbell'},
  { externalId:'sq9',movimiento:'sq',tipo:'auxiliar',bloquesIdeal:['H'],rank:'A',nombre:'Step up con mancuerna',altNombre:'Dumbbell step-up',musculosObjetivo:['Gluteo','Cuadriceps','Estabilidad'],transferencia:58,tecnicaClave:'Caja a altura de rodilla. Subes empujando con el talon del pie sobre la caja no con el pie de abajo.',cuandoUsarlo:'Variacion unilateral sin carga axial. Util en lesiones de espalda.',erroresComunes:'Empujarse con el pie de abajo. Inclinarse hacia adelante.',cargaRecomendada:'Mancuernas moderadas.',seriesRecomendadas:'3x10-12 por pierna RIR 3',referencia:'step up exercise tutorial Ben Patrick Bret Contreras'},
  { externalId:'sq10',movimiento:'sq',tipo:'auxiliar',bloquesIdeal:['H'],rank:'A',nombre:'Extension de cuadriceps',altNombre:'Leg extension machine',musculosObjetivo:['Cuadriceps','VMO'],transferencia:52,tecnicaClave:'Extension completa hasta lockout. Sostenes 1-2 seg arriba con contraccion maxima. Bajada excentrica lenta 3 seg.',cuandoUsarlo:'Volumen extra de cuadriceps de bajo riesgo. Ideal al final de la sesion.',erroresComunes:'No llegar al lockout completo. Usar impulso. Bajar demasiado rapido.',cargaRecomendada:'Ligero-moderado.',seriesRecomendadas:'3x12-15',referencia:'leg extension VMO activation hypertrophy Jeff Nippard'},
  { externalId:'sq11',movimiento:'sq',tipo:'variante',bloquesIdeal:['H'],rank:'B',nombre:'Zercher squat',altNombre:'Sentadilla Zercher',musculosObjetivo:['Cuadriceps','Core','Biceps'],transferencia:60,tecnicaClave:'Barra en el pliegue del codo. Los antebrazos paralelos al suelo. Postura muy vertical. Alta demanda de core y de la cadena anterior.',cuandoUsarlo:'Variedad extrema. Refuerza el core frontal y la postura vertical.',erroresComunes:'Dejar que los codos caigan y la barra ruede. No mantener el core tenso.',cargaRecomendada:'Significativamente menos que el basico.',seriesRecomendadas:'3x6-10',referencia:'zercher squat tutorial Alan Thrall'},
  { externalId:'sq12',movimiento:'sq',tipo:'auxiliar',bloquesIdeal:['H'],rank:'B',nombre:'Front squat',altNombre:'Sentadilla frontal con barra',musculosObjetivo:['Cuadriceps','Core','Dorsal'],transferencia:64,tecnicaClave:'Barra sobre los deltoides frontales. Agarre en rack con codos muy altos. Torso completamente vertical.',cuandoUsarlo:'Complemento al back squat. Muy alta demanda de cuadriceps.',erroresComunes:'Codos que caen y la barra se cae. Movilidad insuficiente de munecas.',cargaRecomendada:'Moderado. Suele moverse 70-80% del peso de la sentadilla trasera.',seriesRecomendadas:'3x5-8',referencia:'front squat tutorial powerlifting Squat University Clarence Kennedy'},
  { externalId:'bp1',movimiento:'bp',tipo:'variante',bloquesIdeal:['H','F','V'],rank:'S',nombre:'Banca con pausa 2-3ct',altNombre:'Pause bench press',musculosObjetivo:['Pectoral','Triceps','Leg drive'],transferencia:97,tecnicaClave:'Descendes a velocidad normal. Tocas el pecho y pausas completamente 2-3 segundos. El leg drive se activa durante la pausa. Empuje explosivo al completar.',cuandoUsarlo:'Atleta que falla en la salida del pecho. Movimiento de competicion con pausa exigida.',erroresComunes:'Rebotar en el pecho. Perder el arco durante la pausa. Leg drive que no se activa durante la pausa.',cargaRecomendada:'Mismos porcentajes que el basico. Ya incluye la pausa de competicion.',seriesRecomendadas:'4x3-5 en fuerza base. 3x5-6 en volumen',referencia:'competition bench press pause tutorial Bryce Lewis Calgary Barbell Chris Duffin'},
  { externalId:'bp2',movimiento:'bp',tipo:'variante',bloquesIdeal:['H','F'],rank:'S',nombre:'Spoto press',altNombre:'2-3cm sobre el pecho sin toque',musculosObjetivo:['Pectoral','Triceps proximal'],transferencia:93,tecnicaClave:'Todo igual que la banca hasta que la barra queda a 2-3cm del pecho sin tocar. Mas dificil que la pausa clasica por la tension isometrica sin apoyo.',cuandoUsarlo:'Atleta que falla la salida del pecho. Mas demandante que la pausa clasica.',erroresComunes:'Tocar el pecho. Perder tension mientras la barra esta suspendida.',cargaRecomendada:'5-10% menos que el basico.',seriesRecomendadas:'4x4-5 en fuerza base',referencia:'spoto press tutorial bench Eric Spoto Stronger by Science'},
  { externalId:'bp3',movimiento:'bp',tipo:'variante',bloquesIdeal:['H'],rank:'A',nombre:'Larsen press',altNombre:'Sin apoyo de piernas',musculosObjetivo:['Pectoral','Triceps','Core'],transferencia:82,tecnicaClave:'Piernas extendidas y suspendidas sin apoyar los pies. Esto elimina completamente el leg drive.',cuandoUsarlo:'Hipertrofia de pecho sin asistencia de piernas. Corrige la dependencia excesiva del leg drive.',erroresComunes:'Arquear la espalda excesivamente sin apoyo de piernas.',cargaRecomendada:'15-20% menos que el basico.',seriesRecomendadas:'3x8-10 RIR 2-3',referencia:'Larsen press bench tutorial Calgary Barbell Greg Nuckols'},
  { externalId:'bp4',movimiento:'bp',tipo:'variante',bloquesIdeal:['H','F'],rank:'A',nombre:'Floor press',altNombre:'Press desde el suelo',musculosObjetivo:['Triceps','Pectoral medio'],transferencia:75,tecnicaClave:'Tumbado en el suelo. Los codos tocan el suelo al final limitando el ROM. Sin leg drive.',cuandoUsarlo:'Atleta que falla el bloqueo final. Menos estres en el hombro.',erroresComunes:'Rebotar los codos en el suelo. Codos a 90 grados del torso.',cargaRecomendada:'Similar a la banca normal o ligeramente menos.',seriesRecomendadas:'3x5-8 en fuerza base. 3x8-12 en hipertrofia',referencia:'floor press powerlifting tutorial Alan Thrall Brian Shaw'},
  { externalId:'bp5',movimiento:'bp',tipo:'variante',bloquesIdeal:['H'],rank:'A',nombre:'Banca inclinada con barra',altNombre:'Incline barbell bench press',musculosObjetivo:['Pectoral superior','Deltoides anterior'],transferencia:68,tecnicaClave:'Banco a 15-30 grados. No mas inclinacion o se convierte en press militar.',cuandoUsarlo:'Hipertrofia del pectoral superior. Atleta con pecho inferior dominante.',erroresComunes:'Inclinacion excesiva mayor a 30 grados.',cargaRecomendada:'15-20% menos que la banca plana.',seriesRecomendadas:'3x8-12 RIR 2-3',referencia:'incline bench press hypertrophy Jeff Nippard Chris Beardsley'},
  { externalId:'bp6',movimiento:'bp',tipo:'auxiliar',bloquesIdeal:['H','F'],rank:'S',nombre:'Press agarre cerrado',altNombre:'Close grip bench press CGB',musculosObjetivo:['Triceps','Pectoral interno'],transferencia:90,tecnicaClave:'Agarre mas cerrado que el habitual. Codos mas cerca del cuerpo. Los triceps toman mas protagonismo.',cuandoUsarlo:'El mejor auxiliar de banca. Atleta que falle el bloqueo final.',erroresComunes:'Agarre demasiado cerrado que estresa munecas. No llegar al lockout.',cargaRecomendada:'Entre 65-80% del RM de banca regular.',seriesRecomendadas:'3x5-8 en fuerza base. 3x8-10 en hipertrofia',referencia:'close grip bench press powerlifting Eric Bugenhagen Calgary Barbell'},
  { externalId:'bp7',movimiento:'bp',tipo:'auxiliar',bloquesIdeal:['H','F'],rank:'A',nombre:'JM Press',altNombre:'Hibrido banca y press frances',musculosObjetivo:['Triceps','Pectoral interno'],transferencia:70,tecnicaClave:'La barra baja hacia la garganta mientras los codos se doblan hacia adelante no hacia afuera.',cuandoUsarlo:'Alternativa al close grip con mas enfasis en triceps.',erroresComunes:'Dejar caer la barra sin control. Codos que vuelan.',cargaRecomendada:'Moderado. Aprende con la barra sola primero.',seriesRecomendadas:'3x6-10',referencia:'JM press tutorial powerlifting JM Blakley EliteFTS'},
  { externalId:'bp8',movimiento:'bp',tipo:'auxiliar',bloquesIdeal:['H'],rank:'A',nombre:'Press frances con mancuerna',altNombre:'Skull crusher con mancuernas',musculosObjetivo:['Triceps cabeza larga'],transferencia:65,tecnicaClave:'Brazos verticales. Solo el antebrazo se mueve. La mancuerna baja hacia la sien.',cuandoUsarlo:'Volumen de triceps en estiramiento. Menor riesgo de codo que con barra.',erroresComunes:'Codo que viaja hacia adelante o hacia atras. Velocidad de bajada excesiva.',cargaRecomendada:'Ligero-moderado.',seriesRecomendadas:'3x10-15 RIR 2-3',referencia:'skull crusher dumbbell form triceps Jeff Nippard Renaissance Periodization'},
  { externalId:'bp9',movimiento:'bp',tipo:'auxiliar',bloquesIdeal:['H'],rank:'A',nombre:'Tate press',altNombre:'Extension lateral de triceps',musculosObjetivo:['Triceps cabeza lateral'],transferencia:62,tecnicaClave:'Mancuernas con palmas hacia adentro. Los codos apuntan hacia afuera. Las mancuernas bajan hacia el pecho por los lados.',cuandoUsarlo:'Trabaja la cabeza lateral del triceps. Ideal al final de la sesion de banca.',erroresComunes:'Llevar las mancuernas demasiado arriba. Peso excesivo.',cargaRecomendada:'Muy ligero. 5-10kg por lado.',seriesRecomendadas:'3x12-20',referencia:'Tate press triceps exercise Dave Tate EliteFTS'},
  { externalId:'bp10',movimiento:'bp',tipo:'auxiliar',bloquesIdeal:['H'],rank:'A',nombre:'Extensiones triceps en polea',altNombre:'Rope tricep pushdown',musculosObjetivo:['Triceps cabeza lateral'],transferencia:60,tecnicaClave:'Polea alta con cuerda. Codos pegados al cuerpo. Al final separas las puntas de la cuerda y sostenes 1 seg.',cuandoUsarlo:'Volumen de triceps de bajo riesgo. Puede hacerse al final de cualquier sesion.',erroresComunes:'Codos que se mueven y el hombro trabaja. No llegar al lockout.',cargaRecomendada:'Ligero.',seriesRecomendadas:'3-4x12-20',referencia:'tricep pushdown cable form Jeff Nippard Chris Beardsley'},
  { externalId:'bp11',movimiento:'bp',tipo:'auxiliar',bloquesIdeal:['H'],rank:'B',nombre:'Press militar con mancuerna',altNombre:'Dumbbell overhead press',musculosObjetivo:['Deltoides','Triceps'],transferencia:54,tecnicaClave:'De pie o sentado. Mancuernas a la altura de los hombros palmas hacia adelante. Press vertical hasta lockout.',cuandoUsarlo:'Volumen de empuje vertical. Salud del hombro.',erroresComunes:'Inclinar el torso hacia atras. No llegar al lockout.',cargaRecomendada:'Moderado.',seriesRecomendadas:'3x10-12 RIR 2-3',referencia:'dumbbell shoulder press form Jeff Nippard Athlean-X'},
  { externalId:'bp12',movimiento:'bp',tipo:'auxiliar',bloquesIdeal:['H'],rank:'B',nombre:'Press inclinado con mancuerna',altNombre:'Incline dumbbell press',musculosObjetivo:['Pectoral superior','Deltoides anterior'],transferencia:72,tecnicaClave:'Mayor ROM que el inclinado con barra porque las mancuernas bajan mas profundo.',cuandoUsarlo:'Hipertrofia de pecho con mayor ROM.',erroresComunes:'Rango de movimiento parcial. Perder la retraccion escapular.',cargaRecomendada:'Moderado.',seriesRecomendadas:'3x10-12 RIR 2-3',referencia:'dumbbell incline press hypertrophy Jeff Nippard Mike Israetel'},
  { externalId:'dl1',movimiento:'dl',tipo:'variante',bloquesIdeal:['H','F','V'],rank:'S',nombre:'DL en deficit 4-6cm',altNombre:'Deficit deadlift',musculosObjetivo:['Isquiotibiales','Gluteo','Cadena posterior'],transferencia:95,tecnicaClave:'Parado sobre un plato o plataforma de 4-6cm. El ROM aumenta porque la barra empieza mas abajo.',cuandoUsarlo:'Atleta que falla en la salida del suelo. Trabaja isquiotibiales y gluteo desde mayor estiramiento.',erroresComunes:'Deficit mayor a 8cm. Espalda que se redondea desde el inicio.',cargaRecomendada:'5-10% menos que el basico.',seriesRecomendadas:'4x3-5 en fuerza base. 3x5-8 en hipertrofia',referencia:'deficit deadlift tutorial Bryce Lewis Calgary Barbell'},
  { externalId:'dl2',movimiento:'dl',tipo:'variante',bloquesIdeal:['F'],rank:'S',nombre:'DL con pausa arriba de rodilla',altNombre:'Paused deadlift knee level',musculosObjetivo:['Gluteo','Bloqueo','Erectores'],transferencia:93,tecnicaClave:'Tiron normal hasta que la barra llega por encima de las rodillas. Pausas 2-3 seg manteniendo toda la tension.',cuandoUsarlo:'Atleta que falla el bloqueo. La pausa obliga a mantener la tension exactamente donde el DL tiende a perderse.',erroresComunes:'Dejar caer la barra despues de la pausa. No empujar la cadera al completar.',cargaRecomendada:'10-15% menos que el basico.',seriesRecomendadas:'4x3 a lo largo del bloque de fuerza base',referencia:'deadlift pause above knee tutorial Calgary Barbell Brian Minor'},
  { externalId:'dl3',movimiento:'dl',tipo:'variante',bloquesIdeal:['H'],rank:'A',nombre:'DL agarre arrancada',altNombre:'Snatch grip deadlift',musculosObjetivo:['Dorsales','Isquiotibiales','Posicion'],transferencia:76,tecnicaClave:'Agarre muy ancho al ancho de los soportes de la barra o mas. Baja las caderas y el torso queda mas inclinado.',cuandoUsarlo:'Hipertrofia de dorsal en patron de DL. Ensena a mantener el pecho arriba.',erroresComunes:'Barra separada del cuerpo. Espalda que se redondea.',cargaRecomendada:'30-40% menos que el basico.',seriesRecomendadas:'3x5-8 RIR 3',referencia:'snatch grip deadlift tutorial Juggernaut Training'},
  { externalId:'dl4',movimiento:'dl',tipo:'variante',bloquesIdeal:['H','F'],rank:'A',nombre:'DL convencional para atletas sumo',altNombre:'Conv DL para especialistas sumo',musculosObjetivo:['Cadena posterior','Isquiotibiales','Erectores'],transferencia:82,tecnicaClave:'Para atleta de sumo: el convencional se convierte en variante auxiliar.',cuandoUsarlo:'La diferencia entre tu sumo y tu convencional revela que musculo esta frenando el desarrollo.',erroresComunes:'Usarlo con el mismo peso que el sumo.',cargaRecomendada:'Generalmente 5-15% menos que el sumo para atletas especialistas.',seriesRecomendadas:'3x4-5',referencia:'conventional deadlift for sumo lifters Calgary Barbell Greg Nuckols'},
  { externalId:'dl5',movimiento:'dl',tipo:'auxiliar',bloquesIdeal:['H','V'],rank:'S',nombre:'RDL Peso Muerto Rumano',altNombre:'Romanian deadlift',musculosObjetivo:['Isquiotibiales','Gluteo','Erectores'],transferencia:91,tecnicaClave:'Desde arriba. Bisagra de cadera llevando el torso hacia adelante mientras la barra baja pegada a las piernas. La bajada es de 3 seg buscando ACTIVAMENTE el estiramiento del isquiotibial.',cuandoUsarlo:'El mejor auxiliar de DL. Trabaja isquiotibiales en estiramiento maximo donde mas crecen.',erroresComunes:'Peso excesivo. Espalda redondeada. No sentir el estiramiento del isquiotibial.',cargaRecomendada:'50-65% del RM de DL.',seriesRecomendadas:'3-4x8-10 RIR 2-3. Prioridad al estiramiento',referencia:'RDL romanian deadlift form Alan Thrall Jeff Nippard'},
  { externalId:'dl6',movimiento:'dl',tipo:'auxiliar',bloquesIdeal:['H','F'],rank:'S',nombre:'Hip thrust pesado',altNombre:'Barbell hip thrust',musculosObjetivo:['Gluteo mayor','Bloqueo'],transferencia:88,tecnicaClave:'Espalda apoyada en el banco a la altura de los omoplatos. Barra sobre las caderas con almohadilla. Empujas la cadera hacia arriba hasta extension completa. Sostenes 1-2 seg arriba.',cuandoUsarlo:'Atleta que falla el bloqueo en sumo. El gluteo en extension de cadera es el motor del bloqueo sumo.',erroresComunes:'No llegar a la extension completa. La barra se desplaza.',cargaRecomendada:'Progresion semanal de 5kg.',seriesRecomendadas:'4x8-10 en hipertrofia. 4x6-8 en fuerza base',referencia:'hip thrust tutorial barbell Bret Contreras el inventor'},
  { externalId:'dl7',movimiento:'dl',tipo:'auxiliar',bloquesIdeal:['H','F'],rank:'A',nombre:'Good morning DL',altNombre:'Good morning cadena posterior',musculosObjetivo:['Erectores','Isquiotibiales','Gluteo'],transferencia:78,tecnicaClave:'Barra en la espalda. Bisagra de cadera con espalda neutral. El angulo del torso es similar al inicio del tiron de DL.',cuandoUsarlo:'Atleta con espalda baja que se redondea en el DL.',erroresComunes:'Espalda redondeada NUNCA. Peso excesivo.',cargaRecomendada:'Muy ligero.',seriesRecomendadas:'3x8-12',referencia:'good morning exercise deadlift accessory Alan Thrall Mark Rippetoe'},
  { externalId:'dl8',movimiento:'dl',tipo:'auxiliar',bloquesIdeal:['H'],rank:'A',nombre:'RDL unilateral',altNombre:'Single leg Romanian deadlift',musculosObjetivo:['Isquiotibiales','Gluteo medio','Estabilidad'],transferencia:70,tecnicaClave:'Una pierna en el suelo la otra en el aire. La barra o mancuerna baja mientras el torso baja y la pierna trasera sube.',cuandoUsarlo:'Detecta diferencias de fuerza entre piernas. Gluteo medio activo clave para la estabilidad en sumo.',erroresComunes:'Rotar la cadera durante el movimiento.',cargaRecomendada:'Mancuerna liviana.',seriesRecomendadas:'3x8-10 por pierna RIR 3',referencia:'single leg RDL form unilateral Bret Contreras Jeff Nippard'},
  { externalId:'dl9',movimiento:'dl',tipo:'auxiliar',bloquesIdeal:['H'],rank:'A',nombre:'Trap bar deadlift',altNombre:'Hex bar deadlift',musculosObjetivo:['Cuadriceps','Gluteo','Cadena posterior'],transferencia:62,tecnicaClave:'Parado dentro de la barra hexagonal. La posicion es intermedia entre sentadilla y peso muerto.',cuandoUsarlo:'Atleta con historial de lesiones lumbares. Variabilidad con menor riesgo.',erroresComunes:'Rodillas que colapsan hacia adentro.',cargaRecomendada:'Generalmente mas que el convencional.',seriesRecomendadas:'3x5-8',referencia:'trap bar hex bar deadlift form tutorial Alan Thrall Mark Bell'},
  { externalId:'dl10',movimiento:'dl',tipo:'auxiliar',bloquesIdeal:['F'],rank:'B',nombre:'Rack pull desde la rodilla',altNombre:'Rack pull mid-shin level',musculosObjetivo:['Trapecios','Bloqueo','Agarre'],transferencia:56,tecnicaClave:'La barra arranca de soportes a la altura de las rodillas. Solo trabajas la fase superior del DL.',cuandoUsarlo:'Atleta con bloqueo debil que necesita sobrecarga en la fase final.',erroresComunes:'Usarlo como sustituto del DL completo.',cargaRecomendada:'110-130% del RM de DL.',seriesRecomendadas:'3x3-5',referencia:'rack pull deadlift tutorial Brian Shaw Eddie Hall'},
  { externalId:'dl11',movimiento:'dl',tipo:'auxiliar',bloquesIdeal:['H','V'],rank:'S',nombre:'Curl femoral tumbado DL',altNombre:'Lying leg curl support',musculosObjetivo:['Isquiotibiales','Popliteo'],transferencia:85,tecnicaClave:'Tumbado boca abajo en la maquina. Subes contrayendo el isquio hasta 90 grados. Bajada excentrica de 3 segundos minimo.',cuandoUsarlo:'Equilibrio isquio-cuadriceps que protege la rodilla en sentadilla y DL.',erroresComunes:'Bajar demasiado rapido. Las caderas que se despegan del banco.',cargaRecomendada:'Ligero-moderado.',seriesRecomendadas:'3x10-15 con bajada de 3 seg',referencia:'leg curl form hamstrings hypertrophy Jeff Nippard Chris Beardsley'},
  { externalId:'co1',movimiento:'comp',tipo:'compensatorio',bloquesIdeal:['H','F','V','P'],rank:'S',nombre:'Face pull en polea alta',altNombre:'Cable face pull high pulley',musculosObjetivo:['Manguito rotador','Deltoides posterior','Romboides'],transferencia:98,tecnicaClave:'Polea alta con cuerda. Agarras con los pulgares hacia arriba. Jalas hacia la cara separando las manos al final. Rotacion externa maxima al final.',cuandoUsarlo:'El preventivo mas importante para cualquier atleta de banca. Siempre en todos los bloques.',erroresComunes:'No hacer la rotacion externa al final. Codos que bajan.',cargaRecomendada:'Muy ligero. 15-25 reps.',seriesRecomendadas:'3x15-20. Despues de cada sesion de banca',referencia:'face pull tutorial shoulder health Jeff Cavaliere Athlean-X Chad Wesley Smith'},
  { externalId:'co2',movimiento:'comp',tipo:'compensatorio',bloquesIdeal:['H','F','V','P'],rank:'S',nombre:'Remo Pendlay',altNombre:'Pendlay row',musculosObjetivo:['Dorsal','Romboides','Biceps'],transferencia:95,tecnicaClave:'La barra arranca del suelo en cada rep. Espalda paralela al suelo casi horizontal. Jalas explosivo hacia el abdomen bajo.',cuandoUsarlo:'El remo mas especifico para powerlifting por la posicion de espalda similar al DL.',erroresComunes:'Espalda que se levanta y ya no es Pendlay.',cargaRecomendada:'Pesado. Generalmente entre el 50-70% del RM de DL.',seriesRecomendadas:'4x6-8 RIR 2-3',referencia:'Pendlay row tutorial Glenn Pendlay el creador Alan Thrall'},
  { externalId:'co3',movimiento:'comp',tipo:'compensatorio',bloquesIdeal:['H','F','V','P'],rank:'S',nombre:'Jalon agarre neutro',altNombre:'Neutral grip lat pulldown',musculosObjetivo:['Dorsal ancho','Biceps','Infraespinoso'],transferencia:92,tecnicaClave:'Escapulas abajo y atras antes de jalar. Jalas hasta que las manos lleguen al pecho.',cuandoUsarlo:'Dorsal ancho clave para barra pegada en DL y estabilidad escapular en banca.',erroresComunes:'Jalar con los brazos antes de activar las escapulas.',cargaRecomendada:'Moderado.',seriesRecomendadas:'3-4x10-12 RIR 2-3',referencia:'lat pulldown neutral grip form Jeff Nippard Greg Nuckols'},
  { externalId:'co4',movimiento:'comp',tipo:'compensatorio',bloquesIdeal:['H','F'],rank:'S',nombre:'Copenhague isometrico',altNombre:'Copenhagen adduction hold',musculosObjetivo:['Aductor','Core lateral','Gluteo medio'],transferencia:92,tecnicaClave:'En posicion de plancha lateral con el pie de arriba apoyado en un banco. Activas el aductor de la pierna superior para mantener la posicion. 10-20 seg por lado.',cuandoUsarlo:'El aductor mas olvidado en powerlifting. Clave en sentadilla con apertura amplia y en sumo.',erroresComunes:'Cadera que cae. Tiempo demasiado corto.',cargaRecomendada:'Peso corporal para empezar.',seriesRecomendadas:'3x10-20 seg por lado',referencia:'Copenhagen plank adductor exercise fisioterapia deportiva'},
  { externalId:'co5',movimiento:'comp',tipo:'compensatorio',bloquesIdeal:['H','F','V','P'],rank:'S',nombre:'Ab wheel rueda abdominal',altNombre:'Ab wheel rollout',musculosObjetivo:['Core anterior','Dorsales','Hombros'],transferencia:86,tecnicaClave:'Arrodillado. La rueda sale desde debajo de los hombros. Extiendes lo maximo que puedas SIN que la espalda baja colapse.',cuandoUsarlo:'El ejercicio de core mas especifico para powerlifting. Trabaja anti-extension.',erroresComunes:'Colapsar la zona lumbar al extender.',cargaRecomendada:'Peso corporal.',seriesRecomendadas:'3x5-8 al principio',referencia:'ab wheel rollout tutorial progression Jeff Nippard Tom Merrick'},
  { externalId:'co6',movimiento:'comp',tipo:'compensatorio',bloquesIdeal:['H','F','V','P'],rank:'S',nombre:'Pajaro con mancuerna',altNombre:'Rear delt fly dumbbell',musculosObjetivo:['Deltoides posterior','Manguito rotador'],transferencia:82,tecnicaClave:'Inclinado hacia adelante. Subes la mancuerna hacia el lado no hacia adelante.',cuandoUsarlo:'Deltoides posterior es el mas descuidado en powerlifting. Equilibra la dominancia del deltoides anterior.',erroresComunes:'Mover las mancuernas hacia adelante que ya es remo. Peso excesivo.',cargaRecomendada:'Muy ligero. 5-12kg.',seriesRecomendadas:'3x12-20 RIR 3',referencia:'rear delt fly form tutorial Jeff Nippard John Meadows'},
  { externalId:'co7',movimiento:'comp',tipo:'compensatorio',bloquesIdeal:['H','F','V','P'],rank:'A',nombre:'Remo sentado en polea',altNombre:'Seated cable row neutral grip',musculosObjetivo:['Romboides','Dorsal','Trapecio medio'],transferencia:82,tecnicaClave:'Retraccion escapular completa al final. El pecho permanece afuera durante todo el movimiento.',cuandoUsarlo:'Espalda media. Volumen alto con bajo riesgo. Ideal para altos volumenes de tiron sin fatiga lumbar.',erroresComunes:'Usar el torso para hacer impulso.',cargaRecomendada:'Moderado.',seriesRecomendadas:'3-4x10-12 RIR 2-3',referencia:'seated cable row form powerlifting Jeff Nippard Chris Beardsley'},
  { externalId:'co8',movimiento:'comp',tipo:'compensatorio',bloquesIdeal:['H','F'],rank:'A',nombre:'Seal row',altNombre:'Chest supported row bench',musculosObjetivo:['Dorsal','Retractores escapulares'],transferencia:78,tecnicaClave:'Banco inclinado con el pecho apoyado. Sin impulso posible porque el cuerpo no se puede mover.',cuandoUsarlo:'Cuando hay fatiga lumbar y no se puede hacer Pendlay.',erroresComunes:'Dejar caer las mancuernas sin control.',cargaRecomendada:'Moderado.',seriesRecomendadas:'3x10-12. Aguantas 1 seg al final de cada rep',referencia:'seal row exercise form back Jeff Nippard Mike Israetel'},
  { externalId:'co9',movimiento:'comp',tipo:'compensatorio',bloquesIdeal:['H','F','V','P'],rank:'S',nombre:'Plancha lateral con elevacion',altNombre:'Side plank glute med activation',musculosObjetivo:['Gluteo medio','Core lateral'],transferencia:80,tecnicaClave:'Posicion de plancha lateral apoyado en el antebrazo. La cadera no toca el suelo.',cuandoUsarlo:'Gluteo medio es el estabilizador lateral de cadera. Clave para el valgo de rodilla en sentadilla.',erroresComunes:'La cadera que se hunde. El cuerpo que rota.',cargaRecomendada:'Peso corporal.',seriesRecomendadas:'3x20-30 seg por lado',referencia:'side plank glute med activation Bret Contreras Dr Stuart McGill'},
  { externalId:'co10',movimiento:'comp',tipo:'compensatorio',bloquesIdeal:['H','F','V','P'],rank:'A',nombre:'Curl biceps barra Z',altNombre:'EZ bar curl biceps',musculosObjetivo:['Biceps','Braquial'],transferencia:70,tecnicaClave:'Codos estaticos al lado del cuerpo. Subes hasta la contraccion maxima. Bajada controlada 2 seg.',cuandoUsarlo:'Prevencion de lesiones de codo y biceps muy frecuentes en atletas con mucho DL y remos.',erroresComunes:'Impulso del cuerpo. Bajar demasiado rapido.',cargaRecomendada:'Ligero-moderado.',seriesRecomendadas:'3-4x12-15 RIR 2-3',referencia:'EZ bar curl form biceps Jeff Nippard Chris Beardsley'},
  { externalId:'co11',movimiento:'comp',tipo:'compensatorio',bloquesIdeal:['H','F','V','P'],rank:'A',nombre:'Elevaciones laterales con mancuerna',altNombre:'Lateral raise deltoid',musculosObjetivo:['Deltoides medial','Supraespinoso'],transferencia:76,tecnicaClave:'Subes lateralmente hasta que los brazos queden paralelos al suelo. Sostenes 1 seg arriba.',cuandoUsarlo:'Deltoides medial es el estabilizador primario del hombro. Esencial en atletas con alta frecuencia de banca.',erroresComunes:'Elevar por encima de paralelo. Impulso del cuerpo.',cargaRecomendada:'Muy ligero. 5-10kg.',seriesRecomendadas:'3x15-20',referencia:'lateral raise form deltoid shoulder health Jeff Nippard Athlean-X'},
  { externalId:'co12',movimiento:'comp',tipo:'compensatorio',bloquesIdeal:['H','F'],rank:'A',nombre:'Pallof press en polea',altNombre:'Pallof press anti rotation core',musculosObjetivo:['Core anti-rotatorio','Oblicuos'],transferencia:75,tecnicaClave:'Polea a la altura del pecho. Extiendes los brazos al frente. La polea jala hacia el lado pero el cuerpo no rota.',cuandoUsarlo:'Core anti-rotatorio que resiste el movimiento lateral en sentadilla y DL.',erroresComunes:'Rotar el cuerpo durante la extension.',cargaRecomendada:'Ligero.',seriesRecomendadas:'3x8-10 por lado sosteniendo 2-3 seg cada rep',referencia:'Pallof press anti rotation core stability Tony Gentilcore Eric Cressey'},
  { externalId:'co13',movimiento:'comp',tipo:'compensatorio',bloquesIdeal:['H','F','V','P'],rank:'A',nombre:'Dominadas Pull-up neutro',altNombre:'Neutral grip pull-up',musculosObjetivo:['Dorsal ancho','Biceps','Core'],transferencia:74,tecnicaClave:'Escapulas abajo y atras antes de jalar. Subes hasta que la barbilla queda por encima de la barra.',cuandoUsarlo:'Masa muscular de dorsal con el propio peso.',erroresComunes:'Kipping o impulso con las caderas.',cargaRecomendada:'Peso corporal, luego con lastre.',seriesRecomendadas:'3x8-10 o hasta fallo si son menos de 8',referencia:'pull up form tutorial neutral grip Jeff Nippard Tom Merrick'},
  { externalId:'co14',movimiento:'comp',tipo:'compensatorio',bloquesIdeal:['H','F','V','P'],rank:'A',nombre:'Remo en punta',altNombre:'Dumbbell row one arm',musculosObjetivo:['Dorsal','Romboides','Biceps'],transferencia:75,tecnicaClave:'Una mano apoyada en un banco. La mancuerna sube jalando el codo hacia atras y arriba.',cuandoUsarlo:'Remo unilateral que detecta diferencias entre lados. Menos fatiga lumbar que el Pendlay.',erroresComunes:'Rotar el torso para ayudarse.',cargaRecomendada:'Moderado-pesado.',seriesRecomendadas:'3-4x8-12 RIR 2-3',referencia:'dumbbell row form powerlifting one arm Alan Thrall Calgary Barbell'},
  { externalId:'co15',movimiento:'comp',tipo:'compensatorio',bloquesIdeal:['H'],rank:'A',nombre:'Curl martillo alternado',altNombre:'Hammer curl dumbbell',musculosObjetivo:['Braquial','Braquiorradial','Biceps'],transferencia:65,tecnicaClave:'Mancuernas con agarre neutro con pulgar hacia arriba. Alternado.',cuandoUsarlo:'Braquial y braquiorradial complementan el biceps y estabilizan el codo.',erroresComunes:'Impulso del cuerpo. Agarre que rota durante el movimiento.',cargaRecomendada:'Moderado.',seriesRecomendadas:'3x12 por lado RIR 2-3',referencia:'hammer curl form biceps brachialis Jeff Nippard Renaissance Periodization'},
  { externalId:'co16',movimiento:'comp',tipo:'compensatorio',bloquesIdeal:['H'],rank:'B',nombre:'Extension de espalda',altNombre:'Back extension hyperextension',musculosObjetivo:['Erectores','Gluteo'],transferencia:60,tecnicaClave:'Banco romano con las caderas sobre el soporte. El torso cae hacia abajo y subes extendiendo la espalda.',cuandoUsarlo:'Erectores lumbares sin compresion espinal.',erroresComunes:'Hiperextender al llegar arriba.',cargaRecomendada:'Peso corporal, luego plato en el pecho.',seriesRecomendadas:'3x12-15',referencia:'back extension hyperextension form Mark Bell Alan Thrall'},
  { externalId:'co17',movimiento:'comp',tipo:'compensatorio',bloquesIdeal:['H'],rank:'B',nombre:'Cruce en polea baja',altNombre:'Cable fly crossover low',musculosObjetivo:['Pectoral','Cabeza esternal'],transferencia:60,tecnicaClave:'Poleas bajas. Las manos salen desde abajo y se juntan a la altura del pecho. Sostenes la contraccion al cruzar.',cuandoUsarlo:'Hipertrofia del pectoral con tension constante.',erroresComunes:'Doblar demasiado el codo.',cargaRecomendada:'Ligero-moderado.',seriesRecomendadas:'3x12-15 RIR 2-3',referencia:'cable fly chest hypertrophy crossover Jeff Nippard Renaissance Periodization'},
];

// ─── PROTOCOLOS (20 entries from Valkyria_Guia_Protocolos.html) ──────────────

const PROTOCOLOS = [
  {externalId:'p1',nombre:'Series fijas — NxM',subtitulo:'El protocolo base de toda programacion',categoria:'basico',bloques:['H','F','V','P'],nivel:'Todos',descripcion:'El mas simple y mas usado. N series de M repeticiones con el mismo peso.',objetivo:'Acumular volumen controlado. Construir la base de cualquier bloque.',cuandoUsarlo:'Siempre. Es el protocolo por defecto cuando no hay una razon especifica para usar otro.',comoEjecutar:'1. Decides N series y M reps segun el bloque. 2. Eliges el peso objetivo. 3. Haces todas las series con ese peso. 4. Si el RIR real fue mayor al objetivo: subes 2.5-5kg la proxima semana. 5. Si fue correcto: mantienes. 6. Si fue menor: bajas.',errores:'Subir peso cada semana sin importar el RIR real. No respetar el descanso entre series.',ejemplo:'Hack squat: Sem1: 3x10 @ 60kg RIR4 / Sem2: 3x10 @ 65kg RIR3 / Sem3: 4x10 @ 65kg RIR2 / Sem4: 4x10 @ 70kg RIR2',advertencia:'La progresion no es automatica. No subes peso cada semana por calendario. Subes cuando el RIR real confirma que hay margen.',progresion:[{sem:'Sem 1',sch:'3x10',pct:'60-65%',rir:'RIR 4',nota:'Arrancas ligero.'},{sem:'Sem 2',sch:'3x10',pct:'65-70%',rir:'RIR 3',nota:'Subes si el RIR real fue mayor.'},{sem:'Sem 3',sch:'4x10',pct:'70-75%',rir:'RIR 2-3',nota:'Agregas 1 serie.'},{sem:'Sem 4',sch:'4x10',pct:'72-77%',rir:'RIR 2',nota:'Mas pesado.'},{sem:'Sem 5',sch:'4x12',pct:'73-78%',rir:'RIR 2',nota:'Subes reps.'},{sem:'Sem 6',sch:'4x12',pct:'75-80%',rir:'RIR 1-2',nota:'Maximo volumen del bloque.'}]},
  {externalId:'p2',nombre:'Series fijas pesadas — fuerza base',subtitulo:'NxM con carga alta. La columna de los basicos',categoria:'basico',bloques:['F','V','P'],nivel:'Intermedio/Avanzado',descripcion:'Misma logica que el NxM clasico pero con cargas del 78-92% RM en rangos de 2-5 reps.',objetivo:'Activacion neural. Adaptaciones de fuerza en el SNC. Preparacion para cargas de competicion.',cuandoUsarlo:'Bloque de fuerza base para las variantes principales. Bloque de volumen para el basico de competicion.',comoEjecutar:'1. Calculas el peso desde el %RM de competicion. 2. Haces todas las series con ese peso. 3. La progresion es semanal en %: +2.5 a 4% cada semana.',errores:'Subir el % sin reducir el volumen. Mantener 4 series cuando el % ya es 88-90%.',ejemplo:'SQ con pausa Andree: Sem1: 4x4 @ 117kg (78%) / Sem2: 4x4 @ 120kg (80%) / Sem3: 4x3 @ 124kg (83%)',advertencia:'Cuando el % supera el 85% el descanso entre series debe ser de 3-5 minutos minimo.',progresion:[{sem:'Sem 1',sch:'4x4',pct:'78-80%',rir:'RIR 3',nota:'Arranque conservador.'},{sem:'Sem 2',sch:'4x4',pct:'81-83%',rir:'RIR 2-3',nota:'Subes 2-3% RM.'},{sem:'Sem 3',sch:'4x3',pct:'84-86%',rir:'RIR 2',nota:'Bajas 1 rep por serie.'},{sem:'Sem 4',sch:'4x3',pct:'87-89%',rir:'RIR 1-2',nota:'Cargas altas.'},{sem:'Sem 5',sch:'3x3',pct:'89-91%',rir:'RIR 1',nota:'Bajas 1 serie.'}]},
  {externalId:'p3',nombre:'Top Set + Back-offs',subtitulo:'Serie principal maxima + series de descarga',categoria:'basico',bloques:['V','P'],nivel:'Intermedio/Avanzado',descripcion:'Llegas a una serie principal al %RM objetivo (top set). Luego bajas la carga entre 8 y 10% y haces 2-3 series adicionales.',objetivo:'Testear el rendimiento del dia con la top set. Acumular volumen de calidad en los back-offs sin agotar el SNC.',cuandoUsarlo:'Bloque de volumen para el basico principal. Peaking en las primeras semanas.',comoEjecutar:'1. Haces aproximaciones hasta el peso objetivo. 2. Top set: 1 serie al % programado. 3. Bajas 8-10%. 4. Haces 2-3 series adicionales con las mismas reps.',errores:'Hacer mas de 1 top set. Bajar menos del 8% en los back-offs.',ejemplo:'DL sumo Yisus: Top set: 1x5 @ 162kg (80%) / Back-offs: 2x5 @ 146kg (-10%)',advertencia:'Si la top set salio con RIR 0 NO subes la proxima semana aunque sea el plan. El RIR manda sobre el calendario.',progresion:[{sem:'Sem 1',sch:'1x5 + 2x5',pct:'80% + 72%',rir:'RIR 2-3 top',nota:'Cargas conservadoras.'},{sem:'Sem 2',sch:'1x5 + 2x5',pct:'82% + 74%',rir:'RIR 2 top',nota:'Subes 2%.'},{sem:'Sem 3',sch:'1x4 + 2x4',pct:'85% + 77%',rir:'RIR 1-2 top',nota:'Bajas 1 rep.'},{sem:'Sem 4',sch:'1x3 + 2x3',pct:'88% + 80%',rir:'RIR 1 top',nota:'Cerca del maximo.'},{sem:'Sem 5',sch:'1x2 + 2x2',pct:'91% + 83%',rir:'RIR 0-1 top',nota:'Peaking.'}]},
  {externalId:'p4',nombre:'AMRAP — Al maximo de reps con buena tecnica',subtitulo:'As Many Reps As Possible al fallo tecnico',categoria:'avanzado',bloques:['F'],nivel:'Avanzado',descripcion:'Una serie al maximo de repeticiones con buena tecnica a un % dado. El libro RV lo reserva para atletas avanzados en el Sistema Rotativo.',objetivo:'Testear la capacidad real en un % dado. Detectar si el atleta esta sobreestimando o subestimando su RM.',cuandoUsarlo:'Solo atletas avanzados que controlan perfectamente el fallo tecnico. NUNCA en principiantes.',comoEjecutar:'1. Serie de 1 rep al % objetivo para dar confianza. 2. Serie de 2 reps al % objetivo. 3. AMRAP: tantas reps como puedas con tecnica perfecta.',errores:'Llegar al fallo muscular. No saber distinguir fallo tecnico de fallo muscular.',ejemplo:'SQ barra baja avanzado @ 87%: 1x1 / 1x2 / AMRAP: 7 reps / Back-offs: -5%: 4 reps / -10%: 4 reps / -15%: 5 reps',advertencia:'Este protocolo es SOLO para atletas avanzados. Si el atleta no puede distinguir fallo tecnico de fallo muscular: no usar AMRAP.',progresion:[{sem:'Sem 1',sch:'Conf 1r + Conf 2r + AMRAP',pct:'85%',rir:'Al limite tecnico',nota:'Primera vez: objetivo 6-8 reps.'},{sem:'Sem 2',sch:'Conf 1r + Conf 2r + AMRAP',pct:'85%',rir:'Al limite tecnico',nota:'Si hiciste 8+: sube 2-3% la proxima semana.'},{sem:'Sem 3',sch:'Conf 1r + Conf 2r + AMRAP',pct:'87%',rir:'Al limite tecnico',nota:'Mayor peso. Probablemente 5-7 reps.'},{sem:'Sem 4',sch:'Conf 1r + Conf 2r + AMRAP',pct:'87%',rir:'Al limite tecnico',nota:'Si mejoras reps: el SNC se adapto.'}]},
  {externalId:'p5',nombre:'Load Drop — Bajada de carga (RPE)',subtitulo:'Top set al RPE objetivo, luego -% de carga hasta volver al RPE',categoria:'rpe',bloques:['H'],nivel:'Avanzado',descripcion:'Subes carga hasta alcanzar el RPE objetivo (top set). Bajas la carga un % fijo. Haces series hasta que el RPE vuelva al nivel de la top set.',objetivo:'Maximizar el volumen total en una sesion. El volumen se autorregula segun la fatiga real del dia.',cuandoUsarlo:'Bloque de hipertrofia para ejercicios principales. Requiere que el atleta calibre bien el RPE a variaciones de 0.5.',comoEjecutar:'1. Subes hasta alcanzar el RPE objetivo. 2. Bajas el peso un % fijo (ej. 10%). 3. Haces series con las mismas reps. 4. Continuas hasta que el RPE vuelva al RPE de la top set.',errores:'Usar un % de bajada demasiado pequeno. No ser preciso en el RPE.',ejemplo:'Larsen press: Top: 80kg x5 @8 / -10%: 72kg x5 @6 / 72kg x5 @7 / 72kg x5 @7.5 / 72kg x5 @8 (STOP).',advertencia:'El metodo Load Drop es el que mas volumen genera. Usarlo en peaking o fuerza base puede causar sobreentrenamiento.',progresion:[{sem:'Sem 1',sch:'Top @7 + series -10%',pct:'Hasta RPE 7',rir:'RIR aprox 3',nota:'Empiezas con RPE bajo.'},{sem:'Sem 2',sch:'Top @8 + series -10%',pct:'Hasta RPE 8',rir:'RIR aprox 2',nota:'Subes RPE.'},{sem:'Sem 3',sch:'Top @8 + series -8%',pct:'Hasta RPE 8',rir:'RIR aprox 2',nota:'Bajas el % de caida: mas volumen.'},{sem:'Sem 4',sch:'Top @8-9 + series -8%',pct:'Hasta RPE 8-9',rir:'RIR aprox 1-2',nota:'Maximo estimulo.'}]},
  {externalId:'p6',nombre:'Repeats — Repetir (RPE)',subtitulo:'Top set, luego misma carga hasta que el RPE sube 10%',categoria:'rpe',bloques:['V'],nivel:'Avanzado',descripcion:'Llegas a una top set al RPE objetivo. Mantienes la misma carga y reps. El RPE sube naturalmente. Paras cuando sube 10%.',objetivo:'Mejorar la capacidad de trabajo. Para RPE bajo: aumenta la tolerancia al volumen.',cuandoUsarlo:'Bloque de volumen para el basico de competicion. Requiere precision de RPE a 0.5.',comoEjecutar:'1. Subes hasta el RPE objetivo. 2. Series con la MISMA carga y MISMAS reps. 3. Paras cuando el RPE sube 10% sobre el RPE inicial.',errores:'No registrar el RPE inicial con precision. Parar demasiado pronto o tarde.',ejemplo:'Banca con pausa volumen: Top: 82kg x4 @8 / 82kg x4 @8.5 / 82kg x4 @8.5 / 82kg x4 @9 (STOP).',advertencia:'Este metodo requiere precision de RPE a 0.5 puntos. Sin esa precision el resultado es muy impreciso.',progresion:[{sem:'Sem 1',sch:'Top @7 + repeats hasta @7.7',pct:'Misma carga',rir:'Pocas series',nota:'Estableces el patron.'},{sem:'Sem 2',sch:'Top @8 + repeats hasta @8.8',pct:'Misma carga',rir:'Mas series',nota:'El SNC tolera mas trabajo.'},{sem:'Sem 3',sch:'Top @8 + repeats hasta @8.8',pct:'Misma carga',rir:'Mismo limite',nota:'Progresa el volumen tolerado.'},{sem:'Sem 4',sch:'Top @8.5 + repeats hasta @9.3',pct:'Misma carga',rir:'Limite mas alto',nota:'Bloque de volumen en su punto mas alto.'}]},
  {externalId:'p7',nombre:'Reps Drop — Bajada de repeticiones (RPE)',subtitulo:'Top set, luego misma carga con menos reps',categoria:'rpe',bloques:['P'],nivel:'Intermedio/Avanzado',descripcion:'Llegas a una top set al RPE objetivo. Mantienes la MISMA CARGA pero bajas las reps en las series siguientes.',objetivo:'Adaptaciones neurales. Acumular series con el peso maximo del dia sin el volumen extra.',cuandoUsarlo:'Bloque de peaking exclusivamente. La carga nunca baja, solo las reps.',comoEjecutar:'1. Top set al RPE objetivo. 2. Mantienes la MISMA carga pero bajas 1 rep por serie. 3. Paras cuando el RPE de las series de menos reps vuelve al RPE de la top set.',errores:'Bajar la carga (eso ya seria load drop). Usarlo en hipertrofia.',ejemplo:'DL sumo peaking: Top: 186kg x4 @8 / 186kg x3 @7 / 186kg x3 @8 (STOP).',advertencia:'El reps drop produce el menor volumen total. Eso es intencional en peaking.',progresion:[{sem:'Sem 1',sch:'1x4@8 + 2x3 misma carga',pct:'88-90%',rir:'Top @8',nota:'Estableces el patron.'},{sem:'Sem 2',sch:'1x4@8 + 2x3 + 1x2 misma carga',pct:'89-91%',rir:'Top @8',nota:'Mas volumen en la zona maxima.'},{sem:'Sem 3',sch:'1x3@8.5 + 3x2 misma carga',pct:'91-93%',rir:'Top @8.5',nota:'Cerca del maximo.'},{sem:'Sem 4',sch:'1x2@9 + 2x1 misma carga',pct:'93-96%',rir:'Top @9',nota:'Peaking final.'}]},
  {externalId:'p8',nombre:'Load + Reps Drop — Combinado (RPE)',subtitulo:'Top set, luego baja carga Y reps simultaneamente',categoria:'rpe',bloques:['P'],nivel:'Avanzado',descripcion:'Combinas el load drop y el reps drop simultaneamente. Bajas el peso un % pequeno Y bajas las reps en 1.',objetivo:'Control muy fino de la fatiga en peaking. Para atletas con mucha experiencia en RPE.',cuandoUsarlo:'Solo atletas avanzados. Peaking final 2-3 semanas antes de competicion.',comoEjecutar:'1. Top set al RPE objetivo. 2. Bajas la carga entre 2.5 y 5%. 3. Bajas 1 rep. 4. Series hasta alcanzar el RPE de la top set.',errores:'La complejidad hace que los errores en el RPE tengan mayor impacto. No usar sin experiencia previa en load drop y reps drop por separado.',ejemplo:'Banca peaking: Top: 95kg x4 @8 / Back-off: 92.5kg x3 @7 / 92.5kg x3 @7.5 / 92.5kg x3 @8 (STOP)',advertencia:'El libro RV dice explicitamente que combinarlos conlleva una elevada complejidad. Para la mayoria de atletas usar load drop O reps drop por separado.',progresion:[{sem:'Sem 1',sch:'Top x4@8 + series -2.5% y -1rep',pct:'90-92%',rir:'Alta precision',nota:'Primera vez: pocas series.'},{sem:'Sem 2',sch:'Top x4@8.5 + series -2.5% y -1rep',pct:'91-93%',rir:'Mismo formato',nota:'El atleta ya conoce las sensaciones.'}]},
  {externalId:'p9',nombre:'Progresion lineal simple',subtitulo:'Sube 2.5-5kg cada sesion o semana. Solo principiantes',categoria:'basico',bloques:['H'],nivel:'Solo principiantes',descripcion:'La progresion mas simple posible: subes una cantidad fija de peso cada sesion o cada semana. Funciona mientras el atleta sea principiante.',objetivo:'Establecer el patron de movimiento. Construir la base muscular y neural con el menor riesgo posible.',cuandoUsarlo:'El primer bloque de cualquier principiante. Mientras puedas subir peso cada semana con buena tecnica.',comoEjecutar:'1. Peso comodo con 3-4 reps en el tanque. 2. Siguiente sesion: subes 2.5kg tren superior o 5kg tren inferior. 3. Si no puedes subir: mantienes. 4. Si fallas: bajas 5-10%.',errores:'Subir peso aunque la tecnica no este bien. Pensar que es demasiado simple.',ejemplo:'Frank hack squat: Sem1: 3x10 @ 40kg / Sem2: 3x10 @ 45kg / Sem3: 3x10 @ 50kg / Sem4: 4x10 @ 50kg',advertencia:'Cuando la progresion se detenga 2-3 semanas seguidas: es la senal de que dejo de ser principiante.',progresion:[{sem:'Sem 1',sch:'3x10',pct:'RPE 6 / RIR 4',rir:'Muy comodo',nota:'Estableces el peso base.'},{sem:'Sem 2',sch:'3x10',pct:'+2.5kg sup',rir:'RIR 3-4',nota:'Primera progresion.'},{sem:'Sem 3',sch:'3x10',pct:'+2.5kg',rir:'RIR 3',nota:'Empiezas a sentir el trabajo.'},{sem:'Sem 4',sch:'4x10',pct:'Mismo peso',rir:'RIR 2-3',nota:'Agregas 1 serie.'},{sem:'Sem 5',sch:'4x10',pct:'+2.5kg',rir:'RIR 2-3',nota:'Sigue la progresion.'},{sem:'Sem 6',sch:'4x10',pct:'+2.5kg',rir:'RIR 2',nota:'El estimulo sigue siendo suficiente.'},{sem:'Sem 7',sch:'4x12',pct:'Mismo peso',rir:'RIR 2',nota:'Subes reps.'},{sem:'Sem 8',sch:'4x12',pct:'+2.5kg',rir:'RIR 1-2',nota:'Final del bloque.'}]},
  {externalId:'p10',nombre:'Ondulacion semanal DUP',subtitulo:'Semana A: mas reps menor %. Semana B: menos reps mayor %',categoria:'avanzado',bloques:['F','V'],nivel:'Intermedio/Avanzado',descripcion:'Daily o Weekly Undulating Periodization. La intensidad y el volumen ondulean semana a semana.',objetivo:'Trabajar dos estimulos diferentes en el mismo bloque: hipertrofia y fuerza.',cuandoUsarlo:'Atleta con dos sesiones semanales del mismo basico y objetivos mixtos.',comoEjecutar:'1. Defines dos esquemas: Semana A (mas reps menos %) y Semana B (menos reps mas %). 2. Alternas cada semana. 3. Progresas en AMBAS pistas independientemente.',errores:'Tratar la semana A como descarga. Ambas son igualmente importantes.',ejemplo:'Sentadilla pausa (Lunes A) + Barra alta (Jueves B): Sem1 L: 4x6@117kg / Sem1 J: 5x3@124kg',advertencia:'Si el atleta solo tiene 1 sesion semanal del basico: el DUP no tiene sentido.',progresion:[{sem:'Sem 1 (A)',sch:'4x6',pct:'78%',rir:'RIR 3',nota:'Semana A: mas reps, menos carga.'},{sem:'Sem 2 (B)',sch:'5x3',pct:'83%',rir:'RIR 2',nota:'Semana B: menos reps, mas carga.'},{sem:'Sem 3 (A)',sch:'4x6',pct:'80%',rir:'RIR 2-3',nota:'La pista A sube 2%.'},{sem:'Sem 4 (B)',sch:'5x3',pct:'85%',rir:'RIR 1-2',nota:'La pista B sube 2%.'},{sem:'Sem 5 (A)',sch:'4x6',pct:'82%',rir:'RIR 2',nota:'La pista A sigue subiendo.'},{sem:'Sem 6 (B)',sch:'4x3',pct:'87%',rir:'RIR 1',nota:'La pista B cerca del maximo.'}]},
  {externalId:'p11',nombre:'Cluster sets',subtitulo:'Reps con micro-pausas dentro de la serie',categoria:'tecnica',bloques:['F','P'],nivel:'Avanzado',descripcion:'En vez de hacer N reps seguidas, insertas micro-pausas de 10-20 segundos cada 1-2 reps.',objetivo:'Entrenar con cargas muy altas (90%+) manteniendo alta velocidad en cada rep.',cuandoUsarlo:'Bloque de fuerza base avanzado. Peaking cuando el atleta necesita acostumbrarse a cargas maximas.',comoEjecutar:'1. Carga al % objetivo. 2. Haces 1-2 reps, pausas 10-15 seg. 3. Otras 1-2 reps. 4. Continuas hasta el total programado.',errores:'Micro-pausas demasiado largas (ya es una nueva serie). Usar clusters para hacer mas volumen del que puede recuperar.',ejemplo:'Sentadilla clusters: 3 x (2+2+2) @ 140kg (87.5%) con 15 seg de pausa entre duplas.',advertencia:'El descanso entre clusters debe ser de 3-5 minutos. No es para ahorrar tiempo.',progresion:[{sem:'Sem 1',sch:'(2+2+2) x 3 series',pct:'85%',rir:'Alta calidad cada rep',nota:'Aprendes el ritmo de las pausas.'},{sem:'Sem 2',sch:'(2+2+2) x 4 series',pct:'87%',rir:'Alta calidad cada rep',nota:'Mas series.'},{sem:'Sem 3',sch:'(1+1+1+1) x 4 series',pct:'90%',rir:'Maximo por rep',nota:'Singles con micro-pausa.'}]},
  {externalId:'p12',nombre:'Rest-pause',subtitulo:'Al fallo tecnico, pausa 15-20 seg, continuas',categoria:'tecnica',bloques:['H'],nivel:'Avanzado',descripcion:'Llevas una serie cerca del fallo tecnico. Pausas 15-20 segundos. Haces las reps adicionales que puedas. Genera mucho mas estimulo.',objetivo:'Maximizar el estimulo metabolico con menos tiempo total.',cuandoUsarlo:'Bloque de hipertrofia para auxiliares y compensatorios. NUNCA en los basicos de competicion.',comoEjecutar:'1. Haces reps hasta RIR 1. 2. Dejas la barra. 3. Descansas 15-20 segundos. 4. Haces reps adicionales. 5. Repites hasta el total o fallo.',errores:'Usar rest-pause en los basicos de competicion. Pausas demasiado largas.',ejemplo:'Curl femoral rest-pause: 40kg / 9 reps (RIR 1) / 20 seg / 4 reps / 20 seg / 3 reps. Total: 16 reps.',advertencia:'El rest-pause genera mucha mas fatiga de lo que parece. Empezar con 1 serie por ejercicio.',progresion:[{sem:'Sem 1',sch:'1 x rest-pause 15 reps',pct:'Moderado',rir:'RIR 1',nota:'8r / pausa / 4r / pausa / 3r = 15 total'},{sem:'Sem 2',sch:'1 x rest-pause 18 reps',pct:'Mismo peso',rir:'RIR 1',nota:'Logras mas reps totales.'},{sem:'Sem 3',sch:'Mismo peso mas reps',pct:'Moderado-alto',rir:'Progresa',nota:'Si llegas a 20 reps: subes peso.'}]},
  {externalId:'p13',nombre:'Myo-reps',subtitulo:'Serie de activacion + mini-series de 3-5 reps',categoria:'tecnica',bloques:['H'],nivel:'Avanzado',descripcion:'Una serie de activacion de 12-20 reps cerca del fallo. Luego mini-series de 3-5 reps con 5-10 segundos de pausa.',objetivo:'Maximizar el numero de reps efectivas. Mas eficiente en tiempo que series convencionales.',cuandoUsarlo:'Bloque de hipertrofia para ejercicios de aislamiento y auxiliares en maquinas y poleas.',comoEjecutar:'1. Serie de activacion: 12-20 reps a RIR 1-2. 2. Pausa 5 segundos. 3. Mini-serie: 3-5 reps. 4. Pausa 5 seg. 5. Continuas hasta que la mini-serie baje a 3 reps con RIR 0.',errores:'Pausas demasiado largas. Usar myo-reps en ejercicios libres complejos.',ejemplo:'Extension de cuadriceps: 45kg / 15 reps (RIR 1) / 5seg / 5r / 5seg / 5r / 5seg / 4r / 5seg / 3r (STOP).',advertencia:'Solo usar en maquinas y poleas donde el patron no se compromete con la fatiga.',progresion:[{sem:'Sem 1',sch:'1 x Myo-rep (activ 15r + 3 mini)',pct:'Moderado',rir:'Activ. RIR 2',nota:'15r / 5r / 5r / 3r (STOP).'},{sem:'Sem 2',sch:'1 x Myo-rep (activ 15r + 4 mini)',pct:'Mismo peso',rir:'Activ. RIR 1-2',nota:'Una mini-serie mas.'},{sem:'Sem 3',sch:'2 x Myo-rep separadas 3 min',pct:'Mismo peso',rir:'RIR 1-2',nota:'Doblas el estimulo total.'}]},
  {externalId:'p14',nombre:'Drop set',subtitulo:'Al fallo tecnico bajas el peso y continuas',categoria:'tecnica',bloques:['H'],nivel:'Intermedio/Avanzado',descripcion:'Llevas una serie al fallo tecnico. Sin descanso bajas el peso entre 15 y 25% y continuas.',objetivo:'Alta fatiga muscular en poco tiempo. Maximizar el tiempo bajo tension cerca del fallo.',cuandoUsarlo:'Bloque de hipertrofia para auxiliares en maquinas. Al final de la sesion.',comoEjecutar:'1. Haces una serie al fallo tecnico. 2. Sin descanso (max 5 seg): bajas 15-25%. 3. Continuas hasta el fallo tecnico. 4. Puedes repetir 1-2 veces mas.',errores:'Usar drop sets en los basicos de competicion. Mas de 3 drops.',ejemplo:'Hack squat: 100kg / 12r (fallo) / 80kg / 10r (fallo) / 65kg / 8r (fallo). Total: 30 reps.',advertencia:'Los drop sets generan mucha mas fatiga de lo que parecen. 1 al final de la sesion es suficiente.',progresion:[{sem:'Sem 1',sch:'1 drop (baja 20%)',pct:'Moderado al fallo',rir:'Al fallo tecnico',nota:'Aprendes las sensaciones.'},{sem:'Sem 2',sch:'1 drop (baja 20%)',pct:'Mismo peso',rir:'Al fallo tecnico',nota:'Logras mas reps en el drop.'},{sem:'Sem 3',sch:'2 drops (baja 20% cada vez)',pct:'Mismo peso',rir:'Al fallo tecnico',nota:'Agregar 1 drop extra.'}]},
  {externalId:'p15',nombre:'Piramide ascendente',subtitulo:'Subes el peso cada serie mientras bajas las reps',categoria:'basico',bloques:['H','F','V'],nivel:'Todos',descripcion:'Comienzas con peso ligero y muchas reps. Cada serie subes el peso y bajas las reps.',objetivo:'Calentamiento progresivo integrado. Llegar a la carga maxima del dia con el musculo activado.',cuandoUsarlo:'Bloque de hipertrofia para auxiliares donde quieres explorar la carga maxima.',comoEjecutar:'1. Defines el peso maximo objetivo. 2. Trabajas hacia atras para calcular los pesos anteriores. 3. Cada serie sube 5-15%.',errores:'Llegar demasiado fatigado a la ultima serie. Mas de 4 series.',ejemplo:'Prensa piramide: 60kg x15 / 80kg x12 / 100kg x10 / 120kg x8',advertencia:'Si las series intermedias son demasiado intensas la ultima serie no mostrara el verdadero maximo.',progresion:[{sem:'Serie 1',sch:'1x15',pct:'60%',rir:'RIR 5+',nota:'Activacion.'},{sem:'Serie 2',sch:'1x12',pct:'67%',rir:'RIR 4',nota:'Empieza a sentirse.'},{sem:'Serie 3',sch:'1x10',pct:'74%',rir:'RIR 3',nota:'Ya es trabajo efectivo.'},{sem:'Serie 4',sch:'1x8',pct:'80%',rir:'RIR 2',nota:'Maximo del dia.'}]},
  {externalId:'p16',nombre:'Piramide descendente',subtitulo:'Empiezas pesado y bajas el peso cada serie',categoria:'basico',bloques:['F','V'],nivel:'Intermedio/Avanzado',descripcion:'La primera serie es la mas pesada. Cada serie siguiente bajas el peso y subes las reps.',objetivo:'Maxima performance en la carga mas alta del dia. El SNC fresco permite mejor calidad.',cuandoUsarlo:'Bloque de fuerza base cuando el objetivo es la serie principal pesada.',comoEjecutar:'1. Empiezas con la carga mas alta: pocas reps. 2. Cada serie siguiente bajas el peso y subes reps.',errores:'No calentar correctamente antes de la primera serie pesada.',ejemplo:'DL sumo piramide descendente: 182kg x3 (90%) / 172kg x4 / 162kg x6 / 152kg x8',advertencia:'El calentamiento debe ser extenso antes de la primera serie.',progresion:[{sem:'Serie 1',sch:'1x3',pct:'90%',rir:'RIR 1',nota:'La mas pesada y el SNC esta fresco.'},{sem:'Serie 2',sch:'1x4',pct:'85%',rir:'RIR 2',nota:'Baja el peso sube 1 rep.'},{sem:'Serie 3',sch:'1x6',pct:'80%',rir:'RIR 2-3',nota:'Mas reps a carga moderada.'},{sem:'Serie 4',sch:'1x8',pct:'75%',rir:'RIR 3',nota:'Volumen de calidad.'}]},
  {externalId:'p17',nombre:'Wave loading — Carga en olas',subtitulo:'Semana A pesada, semana B ligera, semana C mas pesada',categoria:'avanzado',bloques:['F','P'],nivel:'Avanzado',descripcion:'La intensidad sube en olas: una semana alta, una semana moderada (deload parcial), una semana mas alta que la primera.',objetivo:'Superar mesetas en atletas avanzados usando el efecto de post-activacion.',cuandoUsarlo:'Atletas avanzados en peaking o fuerza base donde la progresion lineal ya no funciona.',comoEjecutar:'1. Semana 1 (ola alta): carga cercana al maximo. 2. Semana 2 (ola baja): 5-8% menos. 3. Semana 3 (ola mas alta): 3-5% mas que sem 1. 4. Repites el ciclo.',errores:'Hacer la ola baja demasiado facil. Hacer la ola alta demasiado cerca del maximo.',ejemplo:'Banca wave loading: Sem1: 4x3@88kg / Sem2: 4x5@82kg / Sem3: 4x3@92kg',advertencia:'El wave loading no funciona si la progresion lineal todavia funciona.',progresion:[{sem:'Sem 1 (alta)',sch:'4x3',pct:'88%',rir:'RIR 1-2',nota:'Carga alta pero no maxima.'},{sem:'Sem 2 (baja)',sch:'4x5',pct:'82%',rir:'RIR 2-3',nota:'Recuperacion parcial.'},{sem:'Sem 3 (mas alta)',sch:'4x3',pct:'91%',rir:'RIR 1',nota:'Mayor que sem 1.'},{sem:'Sem 4 (alta)',sch:'4x3',pct:'89%',rir:'RIR 1-2',nota:'Inicio del segundo ciclo.'},{sem:'Sem 5 (baja)',sch:'4x5',pct:'83%',rir:'RIR 2-3',nota:'Recuperacion.'},{sem:'Sem 6 (mas alta)',sch:'4x3',pct:'92%',rir:'RIR 0-1',nota:'Mayor que el primer ciclo.'}]},
  {externalId:'p18',nombre:'Superseries — Antagonistas',subtitulo:'Dos ejercicios opuestos seguidos sin descanso entre ellos',categoria:'tecnica',bloques:['H'],nivel:'Todos',descripcion:'Haces un ejercicio y sin descanso haces otro de patron antagonista. Luego descansas.',objetivo:'Eficiencia de sesion: mas trabajo en menos tiempo.',cuandoUsarlo:'Bloque de hipertrofia para auxiliares y compensatorios antagonistas: Biceps/Triceps, Pull/Push.',comoEjecutar:'1. Haces ejercicio A (ej. curl biceps x12). 2. Sin descanso: ejercicio B antagonista (ej. extension triceps x12). 3. Descansar 90-120 seg. 4. Repites N veces.',errores:'Usar superseries con ejercicios que compiten por la misma cadena muscular.',ejemplo:'Biserie brazos: 3x(curl biceps 12r + ext. triceps 12r) con 90 seg de descanso entre biserias.',advertencia:'Las superseries funcionan bien para auxiliares. Para los basicos el descanso completo es mas importante.',progresion:[{sem:'Biserie A',sch:'Curl biceps barra Z',pct:'Moderado',rir:'RIR 2-3',nota:'12-15 reps.'},{sem:'Biserie B',sch:'Ext. triceps cuerda',pct:'Moderado',rir:'RIR 2-3',nota:'12-15 reps. Sin descanso despues de A.'},{sem:'Descanso',sch:'90-120 seg',pct:'',rir:'',nota:'Luego repites la biserie 3-4 veces.'}]},
  {externalId:'p19',nombre:'Tempo training — Control excentrico',subtitulo:'Notacion: X-Y-Z (exc-pausa-conc)',categoria:'tecnica',bloques:['H'],nivel:'Todos',descripcion:'Controlas la velocidad de cada fase del movimiento. La notacion es 3 numeros: X seg excentrica / Y seg pausa / Z seg concentrica.',objetivo:'Mayor estimulo con menos carga. Mejor aprendizaje del patron motor para principiantes.',cuandoUsarlo:'Bloque de hipertrofia para auxiliares. Principiantes para aprender el patron.',comoEjecutar:'1. Eliges el tempo (ej. 3-1-X). 2. El peso sera 20-30% menor que sin tempo. 3. El conteo es preciso.',errores:'Contar demasiado rapido para usar mas peso. Usar tempo en los basicos de competicion.',ejemplo:'Prensa tempo 300 de Frank: 3 seg bajando / sin pausa / explosivo subiendo. Con 60kg se siente como 80kg.',advertencia:'El tempo solo se usa en auxiliares y compensatorios. Nunca en los basicos de competicion.',progresion:[{sem:'Tempo 3-0-X',sch:'3 seg exc',pct:'70-75% del peso sin tempo',rir:'RIR 3',nota:'Para principiantes.'},{sem:'Tempo 3-1-X',sch:'3 seg exc / 1 pausa',pct:'65-70%',rir:'RIR 2-3',nota:'La pausa aumenta la dificultad.'},{sem:'Tempo 4-2-X',sch:'4 seg exc / 2 pausa',pct:'60-65%',rir:'RIR 2',nota:'Maximo TUT.'}]},
  {externalId:'p20',nombre:'Isometric holds — Sostener en posicion',subtitulo:'Contraccion isometrica al final o en el punto de maximo estiramiento',categoria:'tecnica',bloques:['H'],nivel:'Todos',descripcion:'En el punto de maxima contraccion o maximo estiramiento: mantienes la posicion 1-3 segundos antes de continuar.',objetivo:'Mayor activacion muscular en el rango mas dificil. Mejora de la conexion mente-musculo.',cuandoUsarlo:'Bloque de hipertrofia para auxiliares y compensatorios. Principiantes que no sienten el musculo objetivo.',comoEjecutar:'1. Ejecutas el movimiento. 2. En el punto de maximo contraccion: mantienes 1-2 seg. 3. Continuas.',errores:'Sostener en una posicion donde hay estres articular. No aplicar en los basicos.',ejemplo:'Jalon agarre neutro con holds: bajas hasta que las manos lleguen al pecho / sostenes 2 seg / subes lentamente.',advertencia:'Los holds de 2 seg requieren reducir el peso entre 10 y 20%.',progresion:[{sem:'1 seg hold',sch:'Contraccion maxima',pct:'Peso normal',rir:'RIR 3',nota:'Empieza con holds cortos.'},{sem:'2 seg hold',sch:'Contraccion maxima',pct:'Peso normal',rir:'RIR 2-3',nota:'El hold se alarga.'},{sem:'2 seg hold + 2 seg estiramiento',sch:'Ambos extremos',pct:'Peso normal',rir:'RIR 2',nota:'Maximo TUT.'}]},
];

async function main() {
  console.log('Seeding Biblioteca RV...');

  // Upsert ejercicios
  for (const e of EJERCICIOS) {
    await prisma.ejercicioRV.upsert({
      where: { externalId: e.externalId },
      update: {
        nombre: e.nombre,
        altNombre: e.altNombre,
        movimiento: e.movimiento,
        tipo: e.tipo,
        rank: e.rank,
        bloquesIdeal: e.bloquesIdeal,
        musculosObjetivo: e.musculosObjetivo,
        transferencia: e.transferencia,
        tecnicaClave: e.tecnicaClave,
        cuandoUsarlo: e.cuandoUsarlo,
        erroresComunes: e.erroresComunes,
        cargaRecomendada: e.cargaRecomendada,
        seriesRecomendadas: e.seriesRecomendadas,
        referencia: e.referencia,
      },
      create: {
        externalId: e.externalId,
        nombre: e.nombre,
        altNombre: e.altNombre ?? null,
        movimiento: e.movimiento,
        tipo: e.tipo,
        rank: e.rank,
        bloquesIdeal: e.bloquesIdeal,
        musculosObjetivo: e.musculosObjetivo,
        transferencia: e.transferencia,
        tecnicaClave: e.tecnicaClave,
        cuandoUsarlo: e.cuandoUsarlo,
        erroresComunes: e.erroresComunes,
        cargaRecomendada: e.cargaRecomendada,
        seriesRecomendadas: e.seriesRecomendadas,
        referencia: e.referencia ?? null,
      },
    });
  }
  console.log(`✓ ${EJERCICIOS.length} ejercicios RV cargados`);

  // Upsert protocolos
  for (const p of PROTOCOLOS) {
    await prisma.protocoloRV.upsert({
      where: { externalId: p.externalId },
      update: {
        nombre: p.nombre,
        subtitulo: p.subtitulo,
        categoria: p.categoria,
        bloques: p.bloques,
        nivel: p.nivel,
        descripcion: p.descripcion,
        objetivo: p.objetivo,
        cuandoUsarlo: p.cuandoUsarlo,
        comoEjecutar: p.comoEjecutar,
        errores: p.errores,
        ejemplo: p.ejemplo,
        advertencia: p.advertencia,
        progresion: p.progresion,
      },
      create: {
        externalId: p.externalId,
        nombre: p.nombre,
        subtitulo: p.subtitulo ?? null,
        categoria: p.categoria,
        bloques: p.bloques,
        nivel: p.nivel,
        descripcion: p.descripcion,
        objetivo: p.objetivo,
        cuandoUsarlo: p.cuandoUsarlo,
        comoEjecutar: p.comoEjecutar,
        errores: p.errores,
        ejemplo: p.ejemplo,
        advertencia: p.advertencia,
        progresion: p.progresion,
      },
    });
  }
  console.log(`✓ ${PROTOCOLOS.length} protocolos RV cargados`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
